name: Run actions on merged commits
on:
  push:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    if: github.repository == 'UBICenter/openfisca-uk-data'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: uk-policy-engine
          service_account_key: ${{ secrets.POLICYENGINE_UK_DATA_READ }}
          export_default_credentials: true
      - name: Install package
        run: make install
      - name: Download microdata
        run: gsutil cp gs://policyengine-uk-data/raw_frs_2018.h5 raw_frs_2018.h5
      - name: Save microdata
        run: openfisca-uk-data raw_frs save raw_frs_2018.h5 2018
      - name: Run tests
        run: make test
  Publish to PyPI:
    if: github.repository == 'UBICenter/openfisca-uk-data'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Build package
        run: make
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}